/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoprogra.vista;

import javax.swing.JButton;

/**
 *
 * @author Jeremy
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Configuracion = new javax.swing.JButton();
        Aerolíneas = new javax.swing.JButton();
        Vuelos = new javax.swing.JButton();
        VolverBtn = new javax.swing.JButton();
        AgregarClienteBttn = new javax.swing.JButton();
        BuscarCliente = new javax.swing.JButton();
        SalirBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Configuracion.setBackground(new java.awt.Color(51, 255, 153));
        Configuracion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Configuracion.setText("Configuración");

        Aerolíneas.setBackground(new java.awt.Color(51, 255, 153));
        Aerolíneas.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Aerolíneas.setText("Aerolíneas");

        Vuelos.setBackground(new java.awt.Color(51, 255, 153));
        Vuelos.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Vuelos.setText("Vuelos");
        Vuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VuelosActionPerformed(evt);
            }
        });

        VolverBtn.setText("Volver");

        AgregarClienteBttn.setBackground(new java.awt.Color(51, 255, 153));
        AgregarClienteBttn.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        AgregarClienteBttn.setText("Agregar Cliente");
        AgregarClienteBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarClienteBttnActionPerformed(evt);
            }
        });

        BuscarCliente.setBackground(new java.awt.Color(51, 253, 153));
        BuscarCliente.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        BuscarCliente.setText("Buscar Cliente");
        BuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarClienteActionPerformed(evt);
            }
        });

        SalirBttn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SalirBttn.setText("Salir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Configuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Aerolíneas, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AgregarClienteBttn, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Vuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(VolverBtn)))
                        .addGap(0, 247, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SalirBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VolverBtn)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Configuracion)
                    .addComponent(AgregarClienteBttn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aerolíneas)
                    .addComponent(BuscarCliente))
                .addGap(123, 123, 123)
                .addComponent(Vuelos)
                .addGap(37, 37, 37)
                .addComponent(SalirBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getAerolíneas() {
        return Aerolíneas;
    }

    public void setAerolíneas(JButton Aerolíneas) {
        this.Aerolíneas = Aerolíneas;
    }

    public JButton getConfiguracion() {
        return Configuracion;
    }

    public void setConfiguracion(JButton Configuracion) {
        this.Configuracion = Configuracion;
    }

    public JButton getVuelos() {
        return Vuelos;
    }

    public void setVuelos(JButton Vuelos) {
        this.Vuelos = Vuelos;
    }

    public JButton getAgregarClienteBttn() {
        return AgregarClienteBttn;
    }

    public void setAgregarClienteBttn(JButton AgregarClienteBttn) {
        this.AgregarClienteBttn = AgregarClienteBttn;
    }

    private void VuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VuelosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VuelosActionPerformed

    private void AgregarClienteBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarClienteBttnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarClienteBttnActionPerformed

    private void BuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarClienteActionPerformed

    public JButton getBuscarCliente() {
        return BuscarCliente;
    }

    public void setBuscarCliente(JButton BuscarCliente) {
        this.BuscarCliente = BuscarCliente;
    }

    public JButton getVolverBtn() {
        return VolverBtn;
    }

    public void setVolverBtn(JButton VolverBtn) {
        this.VolverBtn = VolverBtn;
    }

    public JButton getSalirBttn() {
        return SalirBttn;
    }

    public void setSalirBttn(JButton SalirBttn) {
        this.SalirBttn = SalirBttn;
    }
    
    public void iniciar()
    {
        setLocationRelativeTo(null);
        setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aerolíneas;
    private javax.swing.JButton AgregarClienteBttn;
    private javax.swing.JButton BuscarCliente;
    private javax.swing.JButton Configuracion;
    private javax.swing.JButton SalirBttn;
    private javax.swing.JButton VolverBtn;
    private javax.swing.JButton Vuelos;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
