/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoprogra.vista;

import javax.swing.JButton;

/**
 *
 * @author XperriX
 */
public class VistaAvion extends javax.swing.JFrame {

    /**
     * Creates new form VistaAvion
     */
    public VistaAvion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        comprarAsientosBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(655, 480));
        setResizable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jLabel1, org.jdesktop.beansbinding.ELProperty.create("${background}"), this, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        getContentPane().setLayout(null);

        jButton1.setText("-");
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 110, 30, 20);

        jButton2.setLabel("-");
        getContentPane().add(jButton2);
        jButton2.setBounds(320, 130, 30, 20);

        jButton3.setLabel("-");
        getContentPane().add(jButton3);
        jButton3.setBounds(320, 150, 30, 20);

        jButton4.setLabel("-");
        getContentPane().add(jButton4);
        jButton4.setBounds(320, 210, 30, 20);

        jButton5.setLabel("-");
        getContentPane().add(jButton5);
        jButton5.setBounds(320, 230, 30, 20);

        jButton6.setLabel("-");
        getContentPane().add(jButton6);
        jButton6.setBounds(320, 250, 30, 20);

        jButton7.setLabel("-");
        getContentPane().add(jButton7);
        jButton7.setBounds(360, 110, 30, 20);

        jButton8.setLabel("-");
        getContentPane().add(jButton8);
        jButton8.setBounds(360, 130, 30, 20);

        jButton9.setLabel("-");
        getContentPane().add(jButton9);
        jButton9.setBounds(360, 150, 30, 20);

        jButton10.setLabel("-");
        getContentPane().add(jButton10);
        jButton10.setBounds(360, 210, 30, 20);

        jButton11.setLabel("-");
        getContentPane().add(jButton11);
        jButton11.setBounds(360, 230, 30, 20);

        jButton12.setLabel("-");
        getContentPane().add(jButton12);
        jButton12.setBounds(360, 250, 30, 20);

        jButton13.setLabel("-");
        getContentPane().add(jButton13);
        jButton13.setBounds(400, 110, 30, 20);

        jButton14.setLabel("-");
        getContentPane().add(jButton14);
        jButton14.setBounds(400, 130, 30, 20);

        jButton15.setLabel("-");
        getContentPane().add(jButton15);
        jButton15.setBounds(400, 150, 30, 20);

        jButton16.setLabel("-");
        getContentPane().add(jButton16);
        jButton16.setBounds(400, 210, 30, 20);

        jButton17.setLabel("-");
        getContentPane().add(jButton17);
        jButton17.setBounds(400, 230, 30, 20);

        jButton18.setLabel("-");
        getContentPane().add(jButton18);
        jButton18.setBounds(400, 250, 30, 20);

        jButton19.setLabel("-");
        getContentPane().add(jButton19);
        jButton19.setBounds(440, 110, 30, 20);

        jButton20.setLabel("-");
        getContentPane().add(jButton20);
        jButton20.setBounds(440, 130, 30, 20);

        jButton21.setLabel("-");
        getContentPane().add(jButton21);
        jButton21.setBounds(440, 150, 30, 20);

        jButton22.setLabel("-");
        getContentPane().add(jButton22);
        jButton22.setBounds(440, 210, 30, 20);

        jButton23.setLabel("-");
        getContentPane().add(jButton23);
        jButton23.setBounds(440, 230, 30, 20);

        jButton24.setLabel("-");
        getContentPane().add(jButton24);
        jButton24.setBounds(440, 250, 30, 20);

        jButton25.setLabel("-");
        getContentPane().add(jButton25);
        jButton25.setBounds(480, 110, 30, 20);

        jButton26.setLabel("-");
        getContentPane().add(jButton26);
        jButton26.setBounds(480, 130, 30, 20);

        jButton27.setLabel("-");
        getContentPane().add(jButton27);
        jButton27.setBounds(480, 150, 30, 20);

        jButton28.setLabel("-");
        getContentPane().add(jButton28);
        jButton28.setBounds(480, 210, 30, 20);

        jButton29.setLabel("-");
        getContentPane().add(jButton29);
        jButton29.setBounds(480, 230, 30, 20);

        jButton30.setLabel("-");
        getContentPane().add(jButton30);
        jButton30.setBounds(480, 250, 30, 20);

        jButton31.setLabel("-");
        getContentPane().add(jButton31);
        jButton31.setBounds(540, 110, 30, 20);

        jButton32.setLabel("-");
        getContentPane().add(jButton32);
        jButton32.setBounds(540, 130, 30, 20);

        jButton33.setLabel("-");
        getContentPane().add(jButton33);
        jButton33.setBounds(540, 150, 30, 20);

        jButton34.setLabel("-");
        getContentPane().add(jButton34);
        jButton34.setBounds(540, 210, 30, 20);

        jButton35.setLabel("-");
        getContentPane().add(jButton35);
        jButton35.setBounds(540, 230, 30, 20);

        jButton36.setLabel("-");
        getContentPane().add(jButton36);
        jButton36.setBounds(540, 250, 30, 20);

        jButton37.setLabel("-");
        getContentPane().add(jButton37);
        jButton37.setBounds(580, 110, 30, 20);

        jButton38.setLabel("-");
        getContentPane().add(jButton38);
        jButton38.setBounds(580, 130, 30, 20);

        jButton39.setLabel("-");
        getContentPane().add(jButton39);
        jButton39.setBounds(580, 150, 30, 20);

        jButton40.setLabel("-");
        getContentPane().add(jButton40);
        jButton40.setBounds(580, 210, 30, 20);

        jButton41.setLabel("-");
        getContentPane().add(jButton41);
        jButton41.setBounds(580, 230, 30, 20);

        jButton42.setLabel("-");
        getContentPane().add(jButton42);
        jButton42.setBounds(580, 250, 30, 20);

        jButton43.setLabel("-");
        getContentPane().add(jButton43);
        jButton43.setBounds(620, 110, 30, 20);

        jButton44.setLabel("-");
        getContentPane().add(jButton44);
        jButton44.setBounds(620, 130, 30, 20);

        jButton45.setLabel("-");
        getContentPane().add(jButton45);
        jButton45.setBounds(620, 150, 30, 20);

        jButton46.setLabel("-");
        getContentPane().add(jButton46);
        jButton46.setBounds(620, 210, 30, 20);

        jButton47.setLabel("-");
        getContentPane().add(jButton47);
        jButton47.setBounds(620, 230, 30, 20);

        jButton48.setLabel("-");
        getContentPane().add(jButton48);
        jButton48.setBounds(620, 250, 30, 20);

        comprarAsientosBtn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        comprarAsientosBtn.setText("Comprar");
        getContentPane().add(comprarAsientosBtn);
        comprarAsientosBtn.setBounds(260, 390, 150, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Plantilla Avion .jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 450);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void iniciar(){
        setLocationRelativeTo(null);
        setVisible(true);
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JButton getjButton10() {
        return jButton10;
    }

    public void setjButton10(JButton jButton10) {
        this.jButton10 = jButton10;
    }

    public JButton getjButton11() {
        return jButton11;
    }

    public void setjButton11(JButton jButton11) {
        this.jButton11 = jButton11;
    }

    public JButton getjButton12() {
        return jButton12;
    }

    public void setjButton12(JButton jButton12) {
        this.jButton12 = jButton12;
    }

    public JButton getjButton13() {
        return jButton13;
    }

    public void setjButton13(JButton jButton13) {
        this.jButton13 = jButton13;
    }

    public JButton getjButton14() {
        return jButton14;
    }

    public void setjButton14(JButton jButton14) {
        this.jButton14 = jButton14;
    }

    public JButton getjButton15() {
        return jButton15;
    }

    public void setjButton15(JButton jButton15) {
        this.jButton15 = jButton15;
    }

    public JButton getjButton16() {
        return jButton16;
    }

    public void setjButton16(JButton jButton16) {
        this.jButton16 = jButton16;
    }

    public JButton getjButton17() {
        return jButton17;
    }

    public void setjButton17(JButton jButton17) {
        this.jButton17 = jButton17;
    }

    public JButton getjButton18() {
        return jButton18;
    }

    public void setjButton18(JButton jButton18) {
        this.jButton18 = jButton18;
    }

    public JButton getjButton19() {
        return jButton19;
    }

    public void setjButton19(JButton jButton19) {
        this.jButton19 = jButton19;
    }

    public JButton getjButton2() {
        return jButton2;
    }

    public void setjButton2(JButton jButton2) {
        this.jButton2 = jButton2;
    }

    public JButton getjButton20() {
        return jButton20;
    }

    public void setjButton20(JButton jButton20) {
        this.jButton20 = jButton20;
    }

    public JButton getjButton21() {
        return jButton21;
    }

    public void setjButton21(JButton jButton21) {
        this.jButton21 = jButton21;
    }

    public JButton getjButton22() {
        return jButton22;
    }

    public void setjButton22(JButton jButton22) {
        this.jButton22 = jButton22;
    }

    public JButton getjButton23() {
        return jButton23;
    }

    public void setjButton23(JButton jButton23) {
        this.jButton23 = jButton23;
    }

    public JButton getjButton24() {
        return jButton24;
    }

    public void setjButton24(JButton jButton24) {
        this.jButton24 = jButton24;
    }

    public JButton getjButton25() {
        return jButton25;
    }

    public void setjButton25(JButton jButton25) {
        this.jButton25 = jButton25;
    }

    public JButton getjButton26() {
        return jButton26;
    }

    public void setjButton26(JButton jButton26) {
        this.jButton26 = jButton26;
    }

    public JButton getjButton27() {
        return jButton27;
    }

    public void setjButton27(JButton jButton27) {
        this.jButton27 = jButton27;
    }

    public JButton getjButton28() {
        return jButton28;
    }

    public void setjButton28(JButton jButton28) {
        this.jButton28 = jButton28;
    }

    public JButton getjButton29() {
        return jButton29;
    }

    public void setjButton29(JButton jButton29) {
        this.jButton29 = jButton29;
    }

    public JButton getjButton3() {
        return jButton3;
    }

    public void setjButton3(JButton jButton3) {
        this.jButton3 = jButton3;
    }

    public JButton getjButton30() {
        return jButton30;
    }

    public void setjButton30(JButton jButton30) {
        this.jButton30 = jButton30;
    }

    public JButton getjButton31() {
        return jButton31;
    }

    public void setjButton31(JButton jButton31) {
        this.jButton31 = jButton31;
    }

    public JButton getjButton32() {
        return jButton32;
    }

    public void setjButton32(JButton jButton32) {
        this.jButton32 = jButton32;
    }

    public JButton getjButton33() {
        return jButton33;
    }

    public void setjButton33(JButton jButton33) {
        this.jButton33 = jButton33;
    }

    public JButton getjButton34() {
        return jButton34;
    }

    public void setjButton34(JButton jButton34) {
        this.jButton34 = jButton34;
    }

    public JButton getjButton35() {
        return jButton35;
    }

    public void setjButton35(JButton jButton35) {
        this.jButton35 = jButton35;
    }

    public JButton getjButton36() {
        return jButton36;
    }

    public void setjButton36(JButton jButton36) {
        this.jButton36 = jButton36;
    }

    public JButton getjButton37() {
        return jButton37;
    }

    public void setjButton37(JButton jButton37) {
        this.jButton37 = jButton37;
    }

    public JButton getjButton38() {
        return jButton38;
    }

    public void setjButton38(JButton jButton38) {
        this.jButton38 = jButton38;
    }

    public JButton getjButton39() {
        return jButton39;
    }

    public void setjButton39(JButton jButton39) {
        this.jButton39 = jButton39;
    }

    public JButton getjButton4() {
        return jButton4;
    }

    public void setjButton4(JButton jButton4) {
        this.jButton4 = jButton4;
    }

    public JButton getjButton40() {
        return jButton40;
    }

    public void setjButton40(JButton jButton40) {
        this.jButton40 = jButton40;
    }

    public JButton getjButton41() {
        return jButton41;
    }

    public void setjButton41(JButton jButton41) {
        this.jButton41 = jButton41;
    }

    public JButton getjButton42() {
        return jButton42;
    }

    public void setjButton42(JButton jButton42) {
        this.jButton42 = jButton42;
    }

    public JButton getjButton43() {
        return jButton43;
    }

    public void setjButton43(JButton jButton43) {
        this.jButton43 = jButton43;
    }

    public JButton getjButton44() {
        return jButton44;
    }

    public void setjButton44(JButton jButton44) {
        this.jButton44 = jButton44;
    }

    public JButton getjButton45() {
        return jButton45;
    }

    public void setjButton45(JButton jButton45) {
        this.jButton45 = jButton45;
    }

    public JButton getjButton46() {
        return jButton46;
    }

    public void setjButton46(JButton jButton46) {
        this.jButton46 = jButton46;
    }

    public JButton getjButton47() {
        return jButton47;
    }

    public void setjButton47(JButton jButton47) {
        this.jButton47 = jButton47;
    }

    public JButton getjButton48() {
        return jButton48;
    }

    public void setjButton48(JButton jButton48) {
        this.jButton48 = jButton48;
    }

    public JButton getjButton5() {
        return jButton5;
    }

    public void setjButton5(JButton jButton5) {
        this.jButton5 = jButton5;
    }

    public JButton getjButton6() {
        return jButton6;
    }

    public void setjButton6(JButton jButton6) {
        this.jButton6 = jButton6;
    }

    public JButton getjButton7() {
        return jButton7;
    }

    public void setjButton7(JButton jButton7) {
        this.jButton7 = jButton7;
    }

    public JButton getjButton8() {
        return jButton8;
    }

    public void setjButton8(JButton jButton8) {
        this.jButton8 = jButton8;
    }

    public JButton getjButton9() {
        return jButton9;
    }

    public void setjButton9(JButton jButton9) {
        this.jButton9 = jButton9;
    }

    public JButton getComprarAsientosBtn() {
        return comprarAsientosBtn;
    }

    public void setComprarAsientosBtn(JButton comprarAsientosBtn) {
        this.comprarAsientosBtn = comprarAsientosBtn;
    }


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAvion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAvion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAvion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAvion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAvion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comprarAsientosBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
